# server.port=8181 # properties ??

# yml ??

#server:
#  port: 8181

#spring:
#  datasource:
#    url: xxx
#    username: xxx
#    password: xxx

# logging ??? default? info ?? ??? ???? ???
# trace? debug? ?? ??? ????? ?
#logging:
#  level:
#    root: debug


# ??? ?? ? ??? ?? ?? ??
# ??? ??? ??? info ?? ??
# com.example.apibasic.req ??? ?? trace ???? ??? ? ? ??
logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace