# server.port=8181 # properties 방식

# yml 방식

#server:
#  port: 8181

# Database Connection
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/demodb
    username: root
    password: mariadb

# logging ??? default? info ?? ??? ???? ???
# trace? debug? ?? ??? ????? ?
#logging:
#  level:
#    root: debug


# ??? ?? ? ??? ?? ?? ??
# ??? ??? ??? info ?? ??
# com.example.apibasic.req ??? ?? trace ???? ??? ? ? ??
logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace

springdoc:
  swagger-ui:
    path: /myapi.html